# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        language: system
        entry: make format
        types: [python]
    -   id: lint
        name: lint
        language: system
        entry: make lint
        types: [python]
    -   id: test
        name: test
        language: system
        entry: make test
        types: [python]
